### ISSUE TITLE
Dreamer Buffer

### ISSUE THREAD

**Issue by elisaparga19** [Eclectic-Sheep/sheeprl#118]
Hello!

I'm adapting your implementation of Dreamer V1 algorithm for my own environment and I wanted to know how experiences are managed in the replay buffer.
Do you store information of each step in the sequential order so that when you sample a specific sequence length of steps you may have an entire episode or the last part of an episode and the beginning of another?  do you make sure you are sampling complete episodes? do you register in the buffer the episodes containing less steps than the sequence length?

Thanks in advance!

**Comment by michele-milesi** [comment]
Hi!
we store each step sequentially so as not to lose the time correspondence between steps. Moreover, we do not care if we are sampling complete episodes or only a part of it or if the episode is shorter than the `sequence_length`, indeed, the sample function can sample a trajectory that contains the end of an episode and the beginning of the following one. The only thing we care about is that the steps of a trajectory must belong to the same environment (if multiple instances of the environment are run).

**Comment by elisaparga19** [comment]
Thanks for the answer, it was really helpfull :)
