### ISSUE TITLE
Problem in links in "how to use"

### ISSUE THREAD

**Issue by GiacomoPracucci** [Eclectic-Sheep/sheeprl#124]
I tried clicking on the links in the bulleted list (README.md in the repo homepage):

- How to run experiments
- How to change default configurations
- How to work with steps
- How to select observations

But the page that opens is blank with the words "Not Found"
![Screenshot 2023-10-23 142944](https://github.com/Eclectic-Sheep/sheeprl/assets/94844087/cc29bab1-0556-4aed-b031-94b9c23f0a7a)
![Screenshot 2023-10-23 143010](https://github.com/Eclectic-Sheep/sheeprl/assets/94844087/2a13d59d-0497-47e6-80a9-f50cfbecbb8d)

**Comment by michele-milesi** [comment]
Hi @GiacomoPracucci, sorry for the inconvenience.
I opened a PR to fix the links.
Thanks
