### ISSUE TITLE
Package installation on GPU device

### ISSUE THREAD

**Issue by hanshuo-shuo** [Eclectic-Sheep/sheeprl#149]
**I have a thing to discuss about this part and I have no idea why:**

Everything works well when I use Mac M1 locally, I install your package and it runs.

<img width="800" alt="image" src="https://github.com/Eclectic-Sheep/sheeprl/assets/80494218/82b4dd6e-f23a-453b-b1f4-5be7be16ca58">

My GPU device is `NVIDIA A100-SXM4-80GB`

To run your code on GPU device, I first try `pip install -e.` But when I try to run the task, they keep telling me that 

<img width="689" alt="image" src="https://github.com/Eclectic-Sheep/sheeprl/assets/80494218/2c4d3d3c-0e72-43b2-8a09-0e3cbd2a79c4">

And that's how I solve this:
when I change the `torch==2.0.*` into `torch==2.1.*` and reinstall your sheeprl, Then the error won't happen.  

I'm curious because I was bothered by this problem for a day and I wonder if this is a typo or a problem with my gpu device only.

Thank you~

**Comment by belerico** [comment]
Those seem to be related: 

* https://github.com/vllm-project/vllm/issues/384
* https://github.com/sanchit-gandhi/whisper-jax/issues/108

Can you try what has been suggested there? We already know that `torch=2.1` is working, but maybe we can solve it to work even with `torch<2.1`. We will drop a new release with `torch=2.1` soon btw

**Comment by hanshuo-shuo** [comment]
I tried today but feeling confused. I think it is not your setup's problem but rather my device's.  

Maybe we can close this for now~
