### ISSUE TITLE
Bug in the in sticky attack in MineDojo wrapper

### ISSUE THREAD

**Issue by ImKvothe** [Eclectic-Sheep/sheeprl#178]
I think in _convert_action of the MineDojo wrapper in line 195 it should be self._sticky_attack_counter = 0 instead of self._sticky_attack = 0, right now once it stops doing an sticky attack it won't do it again because it is setting the _sticky_attack variable instead of the counter to 0, the sticky_jump just below is done correctly.

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/101863690/e77bd1a2-f3f0-4332-8643-287c48ae166d)

**Comment by michele-milesi** [comment]
Hi @ImKvothe, thanks for reporting this.
Yeah, you are right. I will fix this error as soon as possible.
Thank you
