### ISSUE TITLE
dreamerv3 trouble resuming? freeze?

### ISSUE THREAD

**Issue by Disastorm** [Eclectic-Sheep/sheeprl#187]
Hello, sorry I don't actually know much about the mathematical formulas and whatnot behind rl and the algorithms, I've previously been just training stuff with SB3 PPO.
Anyway, I installed sheeprl and implemented a wrapper for Stable Retro and got it started and I could see the envs running in parallel and the agent doing stuff. However, once it hits the point where its set to "learning_starts" it stops logging anything, although its still taking my CPU and RAM. It was basically sitting here for over 30 minutes with no logs. No idea if its actually doing anything or not, although I suppose I could try again with the visual retro window open so I could check.

```
Rank-0: policy_step=46848, reward_env_2=110.59998321533203
Rank-0: policy_step=50772, reward_env_3=278.8006286621094
Rank-0: policy_step=50904, reward_env_0=309.19964599609375
Rank-0: policy_step=53848, reward_env_1=126.399658203125
Rank-0: policy_step=55596, reward_env_0=268.4999694824219
Rank-0: policy_step=57212, reward_env_2=240.7994842529297
Rank-0: policy_step=59680, reward_env_3=195.09988403320312
Rank-0: policy_step=62880, reward_env_1=362.70013427734375
Rank-0: policy_step=64500, reward_env_0=532.301513671875

```

Any ideas as to what the issue could be?

*edit actually it finally updated, i guess its just really slow after learning starts? Is there a way to run this on GPU?
```
Rank-0: policy_step=64500, reward_env_0=532.301513671875
Rank-0: policy_step=66776, reward_env_2=365.80255126953125
Rank-0: policy_step=66808, reward_env_3=68.799560546875
```

**Comment by Disastorm** [comment]
It looks like its faster now when i use fabric accelerator gpu, ill close this for now.

**Comment by Disastorm** [comment]
I got this error
```
CUDA error: misaligned address
```

What does this mean? Also I'm running on windows btw.

**Comment by Disastorm** [comment]
Also since stable retro can only start one emulator per process, the training works due to the async_vector_env but when i run sheeprl_eval, the env fails because it tries to open two within the same process.

**Comment by Disastorm** [comment]
I figured some ways around this stuff, only thing I'd like to really know is just if there is any way to reduce the memory since it takes so much vram while its training. otherwise ill just close this since its not really an issue.

**Comment by Disastorm** [comment]
I see there are different dreamerv3 model sizes defined in the original paper that reduce memory and speed up performance.

My question is do the transition_model.hidden_size and representation_model.hidden_size change along with the dense_units or any of the other params, or should I just leave those at 1024 for all of the model sizes?

**Comment by balloch** [comment]
I feel like you should leave this open, I am encountering the same error with command:
`python sheeprl.py exp=dreamer_v3 env=dmc env.id=walker_walk "algo.cnn_keys.encoder=[rgb]"`
Hangs at 64k. I'm, 99% sure this isn't a vram problem on my end (A40 barely showed fill)  what was your fix?

**Comment by Disastorm** [comment]
ok I'll open it again.
i made it use gpu. i think its actually just insanely slow on cpu.

Also do you happen to know if this is a problem?
```
site-packages\torchmetrics\utilities\prints.py:43: UserWarning: The ``compute`` method of metric MeanMetric was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
```

**Comment by Disastorm** [comment]
I noticed odd behavior when resuming a checkpoint. it does the pretraining again, even if i change learning_starts=0.
When not-resuming the learning_starts works properly but when resuming im not sure what its doing.

**Comment by belerico** [comment]
Hi @Disastorm, thank you for reporting this! I'll have a look asap 🤟

**Comment by Disastorm** [comment]
oh maybe i see the reason. it looks like the resume yaml isn't getting my algo.total_steps params properly from the command line for some reason. It still has the previous total steps, which explains why it quits as soon as it starts. Can you tell me if i should be using experiment instead or is this supposed to work? Also when exactly would I use experiment vs using regular training? thanks.

**Comment by Disastorm** [comment]
looks like if i modify the values in the old yaml, it works. i change the total_steps and learning_starts to 0 in the old yaml and when resuming the resuming gets those values properly.

**Comment by belerico** [comment]
> I feel like you should leave this open, I am encountering the same error with command: `python sheeprl.py exp=dreamer_v3 env=dmc env.id=walker_walk "algo.cnn_keys.encoder=[rgb]"` Hangs at 64k. I'm, 99% sure this isn't a vram problem on my end (A40 barely showed fill) what was your fix?

If you have used just like that it is possible that you're running the experiment on cpu. To run it on gpu you can run the following command:

```bash
python sheeprl.py exp=dreamer_v3 env=dmc env.id=walker_walk "algo.cnn_keys.encoder=[rgb] fabric.accelerator=gpu
```

and to reduce the memory footprint you can also try to add `fabric.precision=bf16-mixed` to train the model with a mixed precision.
Could you please try this out and tell us if this solves your problem?

**Comment by belerico** [comment]
> I figured some ways around this stuff, only thing I'd like to really know is just if there is any way to reduce the memory since it takes so much vram while its training. otherwise ill just close this since its not really an issue.

To reduce the memory footprint you could try to lower down the model dimension: you could have a look [at this config](https://github.com/Eclectic-Sheep/sheeprl/blob/main/sheeprl/configs/exp/dreamer_v3_100k_ms_pacman.yaml), where the S version of dreamer-v3 is used. You could also try to lower down the `algo.per_rank_batch_size` or `algo.per_rank_sequence_length` and see if it helps

**Comment by belerico** [comment]
> looks like if i modify the values in the old yaml, it works. i change the total_steps and learning_starts in the old yaml and when resuming the resuming gets those values properly.

[This is inteded](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/cli.py#L21) because when we resume from a checkpoint we assume that somethig has gone wrong, so we load the old config from the checkpoint to be resumed and we merge it with the one running now, so everything that you specify from the CLI will be discarded.

Moreover, when you resume from a checkppoint you must ([as explained in our how-to](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/howto/logs_and_checkpoints.md#checkpointing)) specify the entire path to the file `.ckpt` containing the checkpoint to be resumed.

When the checkpoint is resumed, the `start_step` [will be set to the last update saved in the checkpoint file](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/algos/dreamer_v3/dreamer_v3.py#L512C5-L512C15), so that the training can be safely resume from there and [if you haven't saved the buffer in the checkpoint](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/algos/dreamer_v3/dreamer_v3.py#L536C9-L536C38), then the algorithm will collect random data to fill up the new buffer for `learning_starts` steps before starting the actual training.

**Comment by belerico** [comment]
PS I also suggest to install the latest version of sheeprl with `pip install sheeprl==0.5.2`, which faster and better optimized

**Comment by balloch** [comment]
> fabric.accelerator=gpu on command line.

I think this is an indicator that I have done something wrong in my setup. `fabric.accelerator=gpu` doesn't work for me, I have to do `fabric.accelerator=cuda` . I did notice that eventually it did start going again (like yours) but veeeeeeeeeeery slow. original tf dreamer implementation runs about 10x faster, to say nothing of the JAX dreamerv3 implementation (but im not trying to compare against that, apples to oranges, that code is lowkey impossible to work with)

**Comment by balloch** [comment]
> fabric.precision=bf16-mixed

great advice with the fabric=precision

I did rerun it with the accelerator set, and it resumes eventually but it takes a long time. maybe there is some initialization that lightning does that im not used to, and it will speed up over time (jax/flax is like this; the first time operations are run is much longer)?

**Comment by belerico** [comment]
> > fabric.accelerator=gpu on command line.
> 
> I think this is an indicator that I have done something wrong in my setup. `fabric.accelerator=gpu` doesn't work for me, I have to do `fabric.accelerator=cuda` . I did notice that eventually it did start going again (like yours) but veeeeeeeeeeery slow. original tf dreamer implementation runs about 10x faster, to say nothing of the JAX dreamerv3 implementation (but im not trying to compare against that, apples to oranges, that code is lowkey impossible to work with)

Could you quantify your being slow? Consider that even the smallest model (the S-sized one) used to train on the Atari-100k takes around 9/10 hours on a single V100, the same reported by the authors of DV3 with just a "< 1 day". Another thing that can speed up the training is to set the `algo.train_every=N` with `N>1`, meaning that the agent will be trained `algo.per_rank_gradient_steps` times every `N` policy steps, where a policy step is a single forward of the agent to retrieve the action given an observation from the env: if you have `E` envs per process and `P` processes, then for a single environment interaction you will have `E * P` policy steps

**Comment by Disastorm** [comment]
> > looks like if i modify the values in the old yaml, it works. i change the total_steps and learning_starts in the old yaml and when resuming the resuming gets those values properly.
> 
> [This is inteded](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/cli.py#L21) because when we resume from a checkpoint we assume that somethig has gone wrong, so we load the old config from the checkpoint to be resumed and we merge it with the one running now, so everything that you specify from the CLI will be discarded.
> 
> Moreover, when you resume from a checkppoint you must ([as explained in our how-to](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/howto/logs_and_checkpoints.md#checkpointing)) specify the entire path to the file `.ckpt` containing the checkpoint to be resumed.
> 
> When the checkpoint is resumed, the `start_step` [will be set to the last update saved in the checkpoint file](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/algos/dreamer_v3/dreamer_v3.py#L512C5-L512C15), so that the training can be safely resume from there and [if you haven't saved the buffer in the checkpoint](https://github.com/Eclectic-Sheep/sheeprl/blob/2c9c0b39814d62bf213d205b2d14707dd595d10b/sheeprl/algos/dreamer_v3/dreamer_v3.py#L536C9-L536C38), then the algorithm will collect random data to fill up the new buffer for `learning_starts` steps before starting the actual training.

I see, so if i want to intentionally resume training for stuff, thats when I should use "experiments"? Resuming from normal training is actually only intended for when something goes wrong? Is that the primary difference between experiments and normal training?

**Comment by belerico** [comment]
> Is there no way to have the buffer read from the previous run's buffer files?

Right now no, this is done only when you're resuming a checkpoint and you have set `buffer.checkpoint=True`

> So actually manual resuming is not really intended, its considered like "something went wrong"? 

Exactly, if you're resuming we assume that you want to continue with a previous experiment, taking off from where you left

> How do i continuously train something until I think it's good across multiple runs, do I just do what I mentioned above?

Right now you just have to set a higher `algo.total_steps` and train for more time

> Also, if my config screen_size doesn't match my environment am I correct in seeing that it transforms the observation to the config screen_size? And the config screen_size only supports a square, you can't use a rectangle? And it has to be a power of 2? so basically 64x64, 128x128, 256x256, etc ?

Dreamer-v3 works only with the power of 2 for how the CNN encoder is defined and yes, your observation is resized to match the `env.screen_size` variable

**Comment by belerico** [comment]
@balloch @Disastorm, is it ok for you to close the issue?

**Comment by balloch** [comment]
Yes, I think so, very helpful! By slow I mean the default model took ~24 hours to do 1.2 million steps, which isn't bad it's about the speed of dreamerv2, I think it just seemed weird because of that long gap of time to get passed 64k

**Comment by balloch** [comment]
> @balloch @Disastorm, is it ok for you to close the issue?

Ok with me!

**Comment by Disastorm** [comment]
@belerico 
Hey just wondering how this buffer checkpointing works? I have 
```
buffer:
  size: 1000000
  checkpoint: True
```

And so when resuming it doesn't do the pretraining buffer steps anymore, however I noticed the buffer file doesn't ever get updated, the last modified date is just when the first training started. Is this a problem?
