### ISSUE TITLE
[Question] Is there a way to merge checkpoints?

### ISSUE THREAD

**Issue by Disastorm** [Eclectic-Sheep/sheeprl#194]
Just wondering if there is a way to merge checkpoints. Like for example if i have a model that can play part of a level well and then a model that can play a different part well, is there a way to merge them so that the final model can play both parts decently?

**Comment by belerico** [comment]
Hi @Disastorm, there is an interesting article [here](https://towardsdatascience.com/merge-large-language-models-with-mergekit-2118fb392b54): they were talking about LLM merging, but I think that the same idea can be applied here

**Comment by Disastorm** [comment]
I see thanks
