### ISSUE TITLE
Typo of DreamerV3 blog

### ISSUE THREAD

**Issue by LYK-love** [Eclectic-Sheep/sheeprl#197]
Hello, I just found an error in your blog about DreamerV3 (https://eclecticsheep.ai/2023/08/10/dreamer_v3.html). In this article, you wrote symexp function as 
<img width="466" alt="image" src="https://github.com/Eclectic-Sheep/sheeprl/assets/74082944/6b08b6e7-d566-4bac-8f85-f752d260e205">

However, this is incorrect since I can’t derivate original x of symlogl(x) with this symexp. I looked at Hafner’s paper where had
<img width="394" alt="image" src="https://github.com/Eclectic-Sheep/sheeprl/assets/74082944/9e64ec26-87d0-47d6-910c-192b15ec77fe">

So I think it’s a typo in your article.

**Comment by michele-milesi** [comment]
Hi @LYK-love, thanks for reporting.
You are right, it is a typo. I will fix it as soon as possible.
