### ISSUE TITLE
RAM usage constantly increasing while inferencing dreamer v3 "player" ?

### ISSUE THREAD

**Issue by Disastorm** [Eclectic-Sheep/sheeprl#198]
I have a script that inferences the dreamer v3 "player"  ( basically this thing https://github.com/Eclectic-Sheep/sheeprl/blob/0e881536ab145569579d00f0fb95283ab9d1dbd2/sheeprl/algos/dreamer_v3/evaluate.py#L56 )

via get_greedy_action and then doing env.step.
I noticed the memory usage constantly increasing at a steady rate seemingly forever ( around 0.1GB per 50 steps, my model is using 64x64 RGB ). Do you know anything about this?

*edit, i did a loop only on the get_greedy_action function without step or anything else, and it seems that it is the function that constantly increases memory usage. Is this expected? Is this due to the recurrent state? I thought that state has a set size though so it shouldn't be constantly increasing right? It also seems odd this happens during inference but not training?

**Comment by michele-milesi** [comment]
Hi @Disastorm,
I have a few questions for you:

1. Are you using our `./sheeprl/algos/dreamer_v3/evaluate.py` script or did you write your own?
2. Which accelerator are you using? CPU or CUDA or other?
3. When looping over the `get_greedy_action()` function, did you use the `torch.no_grad()`? Its absence could be the reason why RAM usage is constantly increasing.

Please let me know, thanks.

**Comment by Disastorm** [comment]
@michele-milesi 
torch.no_grad fixed the problem thanks.

I was using my own code but it was mostly copied from your evaluate. Didn't copy the "@torch.no_grad()" though.
