### ISSUE TITLE
CUDA out of memory when using GPU

### ISSUE THREAD

**Issue by LYK-love** [Eclectic-Sheep/sheeprl#207]
Hello, I met error
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 1 has a total capacty of 10.91 GiB of which 53.25 MiB is free. Inclu
ding non-PyTorch memory, this process has 10.85 GiB memory in use. Of the allocated memory 10.48 GiB is allocated by PyTorch, and 116.28 MiB is reserv
ed by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation fo
r Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
when training with
```
python sheeprl.py exp=dreamer_v3 env=gym env.id=CarRacing-v2 algo.cnn_keys.encoder=\[rgb\] fabric.accelerator=gpu fabric.strategy=ddp fabric.devices=2
```
or
```
python sheeprl.py exp=dreamer_v3 env=gym env.id=CarRacing-v2 algo.cnn_keys.encoder=\[rgb\] fabric.accelerator=gpu fabric.devices=2
```
or
```
python sheeprl.py exp=dreamer_v3 env=gym env.id=CarRacing-v2 algo.cnn_keys.encoder=\[rgb\] fabric.accelerator=gpu fabric.devices=1
```
My configuration is:
* ubuntu22.04 x86_64
* two nvidia 1080Ti GPUs
* Python=3.10
No other computationally expensive processes running when training.

Even when I train with one GPU, the error still occurs immediately. Should I use a stronger GPU, or there's sth to change in the code? (I didn't change any code of cloned repo)

**Comment by belerico** [comment]
Hi @LYK-love, thank you for reporting this! I think that the problem is related to the dreamer-v3 size: by default the standard experiment, i.e. `exp=dreamer_v3`, create the XL version of the agent:

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/18405289/2ec2b5e5-d5d7-4b96-8de2-952f7d3923ac)

You can try to reduce the model size to the M or S size, while utilizing the float16 precision to further reduce the memory footprint.
An example of S sized agent is [here](https://github.com/Eclectic-Sheep/sheeprl/blob/main/sheeprl/configs/exp/dreamer_v3_100k_ms_pacman.yaml).
In the meantime we can prepare standard dreamer-v3 configs one for every size.

cc @michele-milesi

**Comment by belerico** [comment]
Can you please try out [this branch](https://github.com/Eclectic-Sheep/sheeprl/tree/feature/dv3-size-configs)?
You can now choose the dreamer-v3 agent size with:

```bash
python sheeprl.py exp=dreamer_v3 env=gym env.id=CarRacing-v2 algo=dreamer_v3_M algo.cnn_keys.encoder=\[rgb\] fabric.accelerator=gpu fabric.devices=1 fabric.precision=bf16-mixed algo.learning_starts=1024
```

In the command above i've used the bfloat16 mixed precision from fabric and in the following picture there are the GPU stats:

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/18405289/5f6751ee-1082-426d-aee4-db602e274e15)

**Comment by LYK-love** [comment]
Oh thanks for your response. It's so quick! 

Since my GPUs (two Nvidia 1080Ti s)don't support `bf16-mixed`, I use `16-mixed` instead. I'm running
```sh
python sheeprl.py exp=dreamer_v3 env=gym env.id=CarRacing-v2 algo.cnn_keys.encoder=\[rgb\] algo=dreamer_v3_M fabric.accelerator=gpu fabric.strategy=ddp fabric.devices=2 fabric.precision=16-mixed algo.learning_starts=1024
```
for minutes and haven't met out-of-memory error yet. I'll tell you the training result as soon as I get it.
<img width="923" alt="image" src="https://github.com/Eclectic-Sheep/sheeprl/assets/74082944/aab2f6b7-4251-4a61-8b1e-47bc52be4ae7">


Meanwhile, Is there any way to contribute to sheeprl? I'm doing research about dreamer and I'm going to dig into your code base heavily. I'm hoping to contribute to this project.

Btw thanks for your recommendation of `nvitop` :)

**Comment by belerico** [comment]
Hi @LYK-love, we can continue the discussion here: https://github.com/Eclectic-Sheep/sheeprl/discussions/117
