### ISSUE TITLE
Slow dreamer_v3 XL on crafter on a gtx 1080

### ISSUE THREAD

**Issue by geranim0** [Eclectic-Sheep/sheeprl#227]
Hi,

Was doing some testing for the crafter XL model of dreamer_v3, and on a i7 8700k / gtx 1080, getting a policy step increment at about 0.025 Hz.
Compared to the [~11 Hz advertised](https://github.com/Eclectic-Sheep/sheeprl/tree/main?tab=readme-ov-file#what), it's about 400 times slower. V100 is an upgrade compared to the 1080, but [this comparison table](https://i0.wp.com/timdettmers.com/wp-content/uploads/2023/01/GPUS_Ada_raw_performance3.png?ssl=1) shows a difference quite less than 400x. 

The configs used are the unmodified repo with `exp/dreamer_v3_XL_crafter.yaml`.
Could notice the GPU memory getting up to 7.8/8 GB, was wondering if the cause of the slowdown might be a slow process happening because the model can't fit in the GPU?

For other experiments using the small (S) model, getting more reasonable performance ie. 1.4 Hz on `dreamer_v3_100k_ms_pacman`.

(Still curious though, how does crafter (XL) train at ~11 Hz while the pacman (S) experiment is reported at ~2 Hz)

**Comment by michele-milesi** [comment]
Hi @brodequin-slaps,
in the configs there is no specification of the device to use for training (`fabric.accelerator`).
Did you specify it in the command (something like `python sheeprl.py exp=dreamer_v3_XL_crafter fabric.accelerator=...`)?
If you have not done so, then you are using the CPU. That explains the time difference.

Same for MsPacman, did you specify the accelerator?

Regarding the difference between the S and XL models, you must also take into account how often the model parameters are updated (how often the train function is called). You can check this by looking at the parameters: `algo.train_every` and `algo.per_rank_gradient_steps`.
In addition, the precision used for training can also affect the total time of the experiment. @belerico do you remember which precision we used for these two experiments?

Let me know, thanks.

**Comment by brodequin-slaps** [comment]
Hi @michele-milesi ,

Sorry forgot to mention, I *did* pass the `fabric.accelerator=cuda` for all experiments.

`algo.per_rank_gradient_steps` seems to be the same for all `dreamer_v3` experiments, and `algo.train_every ` is `2` for (XL) crafter, `1` for (S) pacman. It does reduce the gap, but still. Guess hard to tell exactly what's going on without profiling.

**Comment by belerico** [comment]
> In addition, the precision used for training can also affect the total time of the experiment. @belerico do you remember which precision we used for these two experiments?
> 
> Let me know, thanks.

For Atari-100k environments we train full precision (32bit), while for crafter we usually use the fp16 or the bfloat16 (when supported). 

Btw, it is also strange to me how an XL model can fit on a 8GB GPU like the 1080: I can try on my 4060 and see what happens there

**Comment by belerico** [comment]
I can confirm that on a 8GB RTX 4060 (notebook series) Dreamer-V3 XL cannot be run with both fp32 and bf16-mixed precision. This is the error I'm receiving:

```bash
Error executing job with overrides: ['exp=dreamer_v3_XL_crafter', 'fabric.accelerator=gpu', 'algo.learning_starts=1024']
Traceback (most recent call last):
  File "/home/belerico/projects/sheeprl/sheeprl/cli.py", line 330, in run
    run_algorithm(cfg)
  File "/home/belerico/projects/sheeprl/sheeprl/cli.py", line 169, in run_algorithm
    fabric.launch(command, cfg, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 862, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 948, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 953, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/belerico/projects/sheeprl/sheeprl/algos/dreamer_v3/dreamer_v3.py", line 705, in main
    train(
  File "/home/belerico/projects/sheeprl/sheeprl/algos/dreamer_v3/dreamer_v3.py", line 243, in train
    imagined_prior, recurrent_state = world_model.rssm.imagination(imagined_prior, recurrent_state, actions)
  File "/home/belerico/projects/sheeprl/sheeprl/algos/dreamer_v3/agent.py", line 456, in imagination
    recurrent_state = self.recurrent_model(torch.cat((prior, actions), -1), recurrent_state)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 139, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/belerico/projects/sheeprl/sheeprl/algos/dreamer_v3/agent.py", line 311, in forward
    out = self.rnn(feat, recurrent_state)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/belerico/miniconda3/envs/sheeprl-p10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/belerico/projects/sheeprl/sheeprl/models/models.py", line 395, in forward
    hx = update * cand + (1 - update) * hx
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 0 has a total capacity of 7.75 GiB of which 10.06 MiB is free. Including non-PyTorch memory, this process has 7.73 GiB memory in use. Of the allocated memory 7.51 GiB is allocated by PyTorch, and 82.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

@brodequin-slaps how is it possible that you were able to fit an XL model on an 8GB GPU?
@michele-milesi we can post here the results as soon as they are available

**Comment by brodequin-slaps** [comment]
Hi @belerico ,

Not sure why the experiment starts on my end while it gives an error on your end. I can observe my GPU's memory getting fileld up to the max, then the shared GPU mem grows

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/15318348/cd910d22-59fb-418d-b05e-3cc358832640)

Don't know if it could impact anything, but I'm running all this in WSL2

**Comment by belerico** [comment]
It seems that the NVIDIA drivers on Windows let you use the shared-memory when all the dedicated GPU RAM gets saturated (which can be the case given that you're trying to train an XL model on a 8GB GPU with full precision, i.e. fp32). This can be related: microsoft/wsl#10452

BTW i did look into our table and the timing for Crafter comes from a training that I had run back in the days! I'm really sorry for the mistake! We are actually running new experiments with Dreamer-V3 and we will update the scores and timing asap

I'm running an experiment on a [Lightning Studio](https://lightning.ai/studios) with an A10G GPU with the following command:

```bash
python sheeprl.py exp=dreamer_v3_XL_crafter algo.learning_starts=1024 fabric.accelerator=gpu fabric.precision=bf16-mixed
```

The results I'm obtaining are:

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/18405289/60e24514-74bb-4e33-933d-3d9f00fc8930)

As you can see the experiment has run 30K policy steps in approx. 4h 10m: if we suppose a linear trend then we should expect that it will end at 1M policy steps in `10^6 / (3 * 10^4) *  (60 * 4 + 10) / 3600 ~= 2.31d`, which aligns with the author time (`<2 days`), considering that they have trained in full fp16 precision, while we are training with a mixed precision

**Comment by belerico** [comment]
Hi @geranim0, i had to stop the studio due to limited credit. 
This what i have obtained:

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/18405289/75f43556-7ce5-441b-a2e1-1c3fca7d819d)

Again, supposing a linear trend the experiment would have finished in `10^6 / (145000) *  (19 * 60  + 51) / 3600 ~= 2.28d,`
