### ISSUE TITLE
Python 3.11 (and 3.12) support

### ISSUE THREAD

**Issue by MischaU8** [Eclectic-Sheep/sheeprl#260]
Currently `sheeprl` requires Python version >= 3.8 and <3.11 (https://github.com/Eclectic-Sheep/sheeprl/blob/main/pyproject.toml#L27)

Is there a good reason not to support Python 3.11 (which was released 18 months ago) or even 3.12?

**Comment by belerico** [comment]
The reason was that in the beginning python 3.11 was too new. I'll open a new branch asap

**Comment by belerico** [comment]
Hi @MischaU8, ca you try out [this branch](https://github.com/Eclectic-Sheep/sheeprl/tree/feature/upgrade-python)? Python 3.11 should be already supported, for Python 3.12 we have to investigate all the other dependencies and check which is working and which not
