### ISSUE TITLE
Train after every environment reset

### ISSUE THREAD

**Issue by LucaVendruscolo** [Eclectic-Sheep/sheeprl#264]
Hello, 

I have been trying to implement Dreamer into a physical game that is dependent on a high step frequency. I am currently getting a step frequency of around 2Hz on a GTX 4080. Is it possible to run the training after every environment reset rather than every step to increase the step frequency?

[sheeprl.zip](https://github.com/Eclectic-Sheep/sheeprl/files/14951108/sheeprl.zip)

I am running it using python sheeprl.py exp=dreamer_v3 env=BallGame algo.mlp_keys.encoder=[position,QR_position] algo.mlp_keys.encoder=[position,QR_position] algo.cnn_keys.encoder=[] algo.cnn_keys.decoder=[]

**Comment by belerico** [comment]
Hi @LucaVendruscolo, if you're using the main branch now you can control a quantity called replay-ratio, i.e. the number of agent updates per environment interaction (without taking into consideration the action repeat). So for example: if you have a replay-ratio of 0.5 your agent will be updated once every two environment interaction. The only thing you could do right is to lower the replay ratio, say 1/10 or 1/20.
Can you try this and tell us if it's working?
Thank you

**Comment by LucaVendruscolo** [comment]
Hi Belerico. Thanks for the help. That would help yes but it would still have a long pause once every 10-20 steps which the game I have set up cant handle (Its one of those labyrinth marble games controlled by motors and a long pause makes the marble fall into a hole). Is there any way to only have the agent update after every game rather than a certain amount of steps?

**Comment by belerico** [comment]
Right now this can happen only if you know how many steps it takes your env before it resets, in this way you can set the replay-ratio accordingly. The thing that you can do is to remove the `Ratio` class in dreamer_v3.py and have a simple flag that is True only when the env resets, upon which you can train your agent

**Comment by LucaVendruscolo** [comment]
Thank you for the help. I will try and implement that and see how it goes.

**Comment by LucaVendruscolo** [comment]
Hello, I have modified the code with this change in dreamer_v3.py line 664:
![Untitled2](https://github.com/Eclectic-Sheep/sheeprl/assets/71438132/3101db34-2593-4765-ae37-6ed9ac2a99bc)

This successfully trains the environment after every game rather than every step but the performance of dreamer gets greatly impacted. I have a game where the model gets more reward for going further along the path and the environment resets when it touches a wall. 

This is the graph with training at every step:
![Untitled](https://github.com/Eclectic-Sheep/sheeprl/assets/71438132/4024349d-2121-4d8b-9767-e8665c75be29)


This is the graph with training after every game:
![Untitled1](https://github.com/Eclectic-Sheep/sheeprl/assets/71438132/aa75ae28-9180-4f4a-b44d-2a59c4e2efc9)

As you can see it never manages to get to 100 reward which would be the reward for completing the path. Do you have any suggestions on how to change the code in a different way so that it doesn't stop the program from learning as effectively?

**Comment by michele-milesi** [comment]
Hi @LucaVendruscolo, I would try to move the following instruction:
```python
per_rank_gradient_steps = ratio(policy_step / world_size)
```
after the `if reset_envs > 0:`

Something like this:

```python
 # Train the agent
        if update >= learning_starts:
            if reset_envs > 0:
                per_rank_gradient_steps = ratio(policy_step / world_size)
                local_data = rb.sample_tensors(
                    ...
```
In this way, you keep the replay ratio as expected.

Let me know if it works

**Comment by LucaVendruscolo** [comment]
Hello, the change seems to have worked! Thank you very much.

![mazegameTrainAfterGameFixed](https://github.com/Eclectic-Sheep/sheeprl/assets/71438132/270d02cd-33f1-4992-9bd5-ba28dcc4daff)
