### ISSUE TITLE
Question regarding imagination process

### ISSUE THREAD

**Issue by anthony0727** [Eclectic-Sheep/sheeprl#272]
I can't fully understand the imagination process
in https://github.com/Eclectic-Sheep/sheeprl/blob/main/notebooks/dreamer_v3_imagination.ipynb,

from the "context" of beginning of imagination
```
    if i == initial_steps - imagination_steps - 1:
        stochastic_state = player.stochastic_state.clone()
        recurrent_state = player.recurrent_state.clone()
```

the imagination is performed
```
        # imagination step
        imagined_stochastic_state, recurrent_state = world_model.rssm.imagination(
            stochastic_state, recurrent_state, actions
        )
```

but doesn't `stochastic_state_{t-1}` have to be fed into `world_model.rssm.imagination` to output `stochastic_state_{t}`?
i.e.
```
        # imagination step
        stochastic_state, recurrent_state = world_model.rssm.imagination(
            stochastic_state, recurrent_state, actions
        )
```

Really appreciate if you could help me understand this process!

**Comment by anthony0727** [comment]
Thanks for the reply!

but my qusestion is,

https://github.com/Eclectic-Sheep/sheeprl/blob/2bae37985d789a67d569bf37ed937b9445ae9ab8/sheeprl/algos/dreamer_v3/dreamer_v3.py#L235

why isn't "next" stochastic used for next next stochastic like shown in behavior learning?

**Comment by belerico** [comment]
You're super right! Thank you both you and @michele-milesi for spotting that! I thought i was going blind!
I'll fix it up right now

**Comment by belerico** [comment]
Opened [here](https://github.com/Eclectic-Sheep/sheeprl/tree/fix/dv3-notebook) a new branch: can you try it out?

**Comment by anthony0727** [comment]
Yup I think the fix is correct! We can close this issue!

**Comment by anthony0727** [comment]
I have two questions!

1) shouldn't initial `stochastic_state` be flattened s.t. 
```
stochastic_state = player.stochastic_state.view(1, 1, -1).clone()
```
in
```
    if i == initial_steps - imagination_steps - 1:
        stochastic_state = player.stochastic_state.clone()
        recurrent_state = player.recurrent_state.clone()
```


2) shouldn't 0.5 also be added to imagined reconstructed obs? s.t.
```
        rec_obs = world_model.observation_model(imagined_latent_states) + 0.5
```
in
```
 # imagination step
        stochastic_state, recurrent_state = world_model.rssm.imagination(stochastic_state, recurrent_state, actions)
        # update current state
        imagined_latent_states = torch.cat((stochastic_state.view(1, 1, -1), recurrent_state), -1)
        rec_obs = world_model.observation_model(imagined_latent_states)
        step_data["rgb"] = rec_obs["rgb"].unsqueeze(0).detach().cpu().numpy()
```
