### ISSUE TITLE
Missing readme.md in dreamerv3

### ISSUE THREAD

**Issue by zichunxx** [Eclectic-Sheep/sheeprl#297]
Hi! 

Thanks for your excellent work which is a great reference to learn Dreamer.

When reading the dreamerv3 code, I found no corresponding `README.md` in the folder like other algorithms.

Did you forget to upload it?

Thanks.

**Comment by belerico** [comment]
Hi @zichunxx, we didn't forget to upload it: we have three blogposts on our site:

* [Dreamer-V3](https://eclecticsheep.ai/2023/08/10/dreamer_v3.html)
* [Dreamer-V2](https://eclecticsheep.ai/2023/07/06/dreamer_v2.html)
* [Dreamer-V1](https://eclecticsheep.ai/2023/06/16/dreamer_v1.html)

But we definitely add also the missing readmes

**Comment by belerico** [comment]
Absolutely no worries! Thank you for pointing that out
