### ISSUE TITLE
Custom Env: RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by defrag-bambino** [Eclectic-Sheep/sheeprl#306]
I am running a DreamerV3 experiment using a custom PyFlyt env gym wrapper. After about half a million policy_steps, it throws a "RecursionError: maximum recursion depth exceeded while calling a Python object" error.
I assume this is an issue with my particular env? Or the gymnasium wrapper?

```
sheeprl fabric.accelerator=cuda fabric.devices=1 fabric.precision=16-mixed exp=dreamer_v3 algo=dreamer_v3_S env=pyflyt algo.total_steps=5000000 algo.cnn_keys.encoder=[] algo.cnn_keys.decoder=[] algo.mlp_keys.encoder=["vector"] algo.mlp_keys.decoder=["vector"] env.num_envs=16 checkpoint.every=10000 algo.replay_ratio=0.2
``` 

<details><summary>Details</summary>
<p>
....

Rank-0: policy_step=588384, reward_env_2=-106.79999542236328
Rank-0: policy_step=588384, reward_env_3=-105.5999984741211
Rank-0: policy_step=588384, reward_env_4=-107.29999542236328
Rank-0: policy_step=588384, reward_env_5=-122.00004577636719
Rank-0: policy_step=588384, reward_env_6=-111.80001068115234
Rank-0: policy_step=588384, reward_env_7=-106.0
Rank-0: policy_step=588384, reward_env_8=-105.5999984741211
Rank-0: policy_step=588384, reward_env_9=-105.29999542236328
Rank-0: policy_step=588384, reward_env_10=-103.5999984741211
Rank-0: policy_step=588384, reward_env_11=-106.29999542236328
Rank-0: policy_step=588384, reward_env_12=-104.4000015258789
Rank-0: policy_step=588384, reward_env_13=-106.99999237060547
Rank-0: policy_step=588384, reward_env_14=-106.69999694824219
Rank-0: policy_step=588384, reward_env_15=-107.79999542236328
argv[0]=
argv[0]=
                             
                             
ERROR: Received the following error from Worker-6: RecursionError: maximum recursion depth exceeded while calling a Python object
ERROR: Shutting down Worker-6.
ERROR: Raising the last exception back to the main process.
Error executing job with overrides: ['fabric.accelerator=cuda', 'fabric.devices=1', 'fabric.precision=16-mixed', 'exp=dreamer_v3', 'algo=dreamer_v3_S', 'env=pyflyt', 'algo.total_steps=5000000', 'algo.cnn_keys.encoder=[]', 'algo.cnn_keys.decoder=[]', 'algo.mlp_keys.encoder=[vector]', 'algo.mlp_keys.decoder=[vector]', 'env.num_envs=16', 'checkpoint.every=10000', 'algo.replay_ratio=0.2']
Traceback (most recent call last):
  File "/mnt/myremote/sheeprl/sheeprl/cli.py", line 367, in run
    run_algorithm(cfg)
  File "/mnt/myremote/sheeprl/sheeprl/cli.py", line 200, in run_algorithm
    fabric.launch(reproducible(command), cfg, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 845, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 931, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 936, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/mnt/myremote/sheeprl/sheeprl/cli.py", line 196, in wrapper
    return func(fabric, cfg, *args, **kwargs)
  File "/mnt/myremote/sheeprl/sheeprl/algos/dreamer_v3/dreamer_v3.py", line 589, in main
    next_obs, rewards, terminated, truncated, infos = envs.step(
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/vector/vector_env.py", line 204, in step
    return self.step_wait()
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/vector/async_vector_env.py", line 333, in step_wait
    self._raise_if_errors(successes)
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/vector/async_vector_env.py", line 544, in _raise_if_errors
    raise exctype(value)
RecursionError: maximum recursion depth exceeded while calling a Python object

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/usr/local/lib/python3.10/dist-packages/gymnasium/vector/async_vector_env.py:460: UserWarning: WARN: Calling `close` while waiting for a pending call to `step` to complete.
  logger.warn(

</p>
</details>

**Comment by belerico** [comment]
Can you try to add to the CLI args the `env.sync_env=True`?
