### ISSUE TITLE
Custom Environments

### ISSUE THREAD

**Issue by Jackflyingzzz** [Eclectic-Sheep/sheeprl#315]
Hi,

Thank you for developing such an outstanding reinforcement learning platform! I'm currently working on integrating Dreamer V3 with a custom Gym environment using gym.envs.register. Could you please guide me to any tutorials or resources that demonstrate how to train Dreamer V3 on custom environments?

Your help would be greatly appreciated!

Best regards,
Jacky

**Comment by michele-milesi** [comment]
Hi @Jackflyingzzz,
thank you for your patience, I have been a little busy the last few days.
[Here](https://github.com/Eclectic-Sheep/sheeprl/blob/main/howto/add_environment.md) you can find some references on how to add a custom environment.
In a few words: our environments are [Gymnasium](https://gymnasium.farama.org/)-compliant, so, if your custom environment is [Gym](https://www.gymlibrary.dev/index.html)-compliant, you must create a wrapper to make it Gymnasium-compliant.

Let me know if something is not clear, thanks.
