### ISSUE TITLE
[Feature Request] add float32 support for macOS MPS

### ISSUE THREAD

**Issue by JustinGoheen** [Eclectic-Sheep/sheeprl#40]
## Issue
Received the following error on M-Series macOS after running `sheeprl ppo --env_id CartPole-v1`.

`TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead`

## Request
Please add float32 support for macOS MPS.

## Notes
I can help with the PR

**Comment by belerico** [comment]
Same solution as #66: can you try [this branch](https://github.com/Eclectic-Sheep/sheeprl/tree/feature/diambra)?

**Comment by JustinGoheen** [comment]
closing this as I plan to dev on Ubuntu and CUDA
