### ISSUE TITLE
Rendering issue with DreamerV2, V3

### ISSUE THREAD

**Issue by dtch1997** [Eclectic-Sheep/sheeprl#77]
Thanks for fixing #66 . 

I still have issues running Dreamer with DM control. 

What works:
- DreamerV2, DreamerV3 with Gymnasium environments. 
- DM control by itself. 

What doesn't work:
- DreamerV2, DreamerV3 on DM control suite. 

The error seems to be a rendering issue. 
- `GLFWError: (65542) b'GLX: Failed to query GLX version'`
- According to reference https://www.glfw.org/docs/3.4/group__errors.html, this corresponds to `GLFW_NO_WINDOW_CONTEXT`

Changing MUJOCO_GL didn't help. 
- glfw (default): https://pastebin.com/QdK7g5Z9
- `egl`: https://pastebin.com/pXNuBcPD
- `osmesa`: https://pastebin.com/bBPf45UN

Here's my example script that works, with RBG rendering (but not windowed). 
```
import numpy as np
from dm_control import suite

# Load the environment
random_state = np.random.RandomState(42)
env = suite.load('hopper', 'stand', task_kwargs={'random': random_state})

# Simulate episode with random actions
duration = 4  # Seconds
frames = []
ticks = []
rewards = []
observations = []

spec = env.action_spec()
time_step = env.reset()

while env.physics.data.time < duration:

  action = random_state.uniform(spec.minimum, spec.maximum, spec.shape)
  time_step = env.step(action)
  camera0 = env.physics.render(camera_id=0, height=200, width=200)
  camera1 = env.physics.render(camera_id=1, height=200, width=200)
  print(camera0.shape)
```

**Comment by belerico** [comment]
Hi @dtch1997, thanks for reporting this! Yeah, this is a rendering issue. Have you tried, with `osmesa`, to add also `PYOPENGL_PLATFORM=""`? Nothing from the `howtos/learning_in_dmc.md` works? Can you also try to add a fake Display from `pyvirtualdisplay` if you're on an headless machine an see what happens?

**Comment by dtch1997** [comment]
Thanks for responding quickly! 

I am on a machine that has rendering enabled (my laptop). 
`PYOPENGL_PLATFORM` doesn't work. 
The instructions in `howto/learn_in_dmc.md` suggest to install `libglew2.0`, but I can only install `libglew2.2` through the standard package repositories.

**Comment by belerico** [comment]
Have you tried to install `libglew2.2`? Can you try to downgrade `mujoco` to `2.3.3` and `dm_control` to `1.0.11`?
