### ISSUE TITLE
Why is Frame_skip for gymnasium mujoco environments set to zero?

### ISSUE THREAD

**Issue by HiddeLekanne** [Eclectic-Sheep/sheeprl#94]
The default for these environments differs from environment to environment. If you set them all to zero, results become silently incomparable with other benchmarks which use the default values.

Also action_repeat = X is not necessarily equal to frame_skip = X. Mujoco Implementations use fixed step ODEs to solve their environments, meaning larger frame_skips result in larger (less accurate) steps.

**Comment by belerico** [comment]
Hi @HiddeLekanne, it was a leftover from a previous implementation: thanks for spotting out!  
Regarding the `frame_skip` vs `action_repeat`:

* for mujoco (which can be instantiated with the `sheeprl/configs/env/gym.yaml` config changing the `env.id` field) we do not apply any `frame_skip` by default (w/o considering the `frame_skip=0` leftover)
* for dmc we have the `frame_skip` parameter and I think this can be misleading: we can remove that parameter and if one wants to apply the `action_repeat` it will set the `env.action_repeat>=1` field

**Comment by HiddeLekanne** [comment]
Ah I was just worried it was a design decision, and that the idea was to replace any frame_skip parameter with the action_repeat parameter.  I am not doing any dmc anyways so that issue isn't on my radar.

Personally I am doing something with irregular timesteps and have added my own config args for that.

**Comment by belerico** [comment]
Beautiful! I'll have it removed asap
Thanks
